### ISSUE TITLE
No sensors found!

### ISSUE THREAD

**Issue by Quinkink** [Sensirion/libsensors-python#2] opened 2015-10-24 12:49 UTC
Hello,
I have a Sensirion SDP610 and I have not managed to use this library to connect it to my raspi.
I get "No sensors found!" message.
Any insight would be appreciated.
Thanks,
MK

----DETAILS BELOW----
I have wired it :
rp pin 1 - VDD
rp pin 3 - DATA
rp pin 5 - CLOCK
rp pin 9 - GND
with pull up resistors between VCC & DATA and VCC & CLOCK

I have enabled I2C
>lsmod|grep gives:
i2c_dev 6737 0
i2C ic2_bcm2708 6252 0

>sudo i2Cdetect -y 1 gives:
30: -- -- --
40: 40 -- --
50: -- -- 

I have installed python-qt4 & paho-mqtt

and run:
>python sync_example.py (with altered line 27)

**Comment by winkj** [comment] 2015-10-24 21:32
Hi there,

Is this on a generic Raspberry Pi or one from the hackathon from September? 

For this library to work, you'll need a kernel with support for our sensors; it's not part of the standard kernels yet. On the Raspberry Pi's from the hackathon, the kernel source can be found in the home directory for the 'pi' user. If it's not a Pi from the event, please let us know and we'll look for a way to share those drivers with you!

HTH, Johannes

**Comment by Quinkink** [comment] 2015-10-26 11:06
Hello Johannes,
Thank-you for your reply.
Yes my raspi is stock not hackatron.
I would be happy to find the right drivers... If you can point me in the right direction.

Mark LEWIS
CATSAS

**Comment by winkj** [comment] 2015-11-02 23:25
Hi Mark,

We're working on getting the drivers ready, hopefully coming in the next few days. Thanks for your patience!

Best, Johannes

**Comment by Quinkink** [comment] 2015-11-03 16:47
Johannes,
Thank-you for your update. I have thought of this project and almost 
contacted you
again the other day. I didn't want to be rude and messed around with a 
little code
on the side but I have not cracked this yet.
I will continue to wait patiently.
Have a great day!
Mark.

On 03/11/2015 00:25, winkj wrote:
>
> Hi Mark,
>
> We're working on getting the drivers ready, hopefully coming in the 
> next few days. Thanks for your patience!
>
> Best, Johannes
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Sensirion/libsensors-python/issues/2#issuecomment-153191203>.
>

-- 
Mark LEWIS
2 place Louis Jouvet,
38100 Grenoble,
France

+33637521050
kingston.lewis@gmail.com

**Comment by honggoff** [comment] 2015-11-05 07:38
Hi Mark,

I will hopefully be able to publish the driver today. Could you let us know, which sensor you would like to use? Depending on the model, we needed to make some change to the configuration of the raspberry.

Cheers,
david

**Comment by honggoff** [comment] 2015-11-05 15:49
Hi Mark,

I just published the source code of our Linux kernel driver for the flow sensors. You can find it here: https://github.com/Sensirion/sfxx/ If you are familiar with compiling kernel modules, this should be enough to get you started.

**Comment by Quinkink** [comment] 2015-11-06 07:53
Hi David,
I have thr Sensirion SDP610.
I give the compiling of kernel a go you suggested. Although I am not yet familiar with this,
Cheers,
Mark.

**Comment by Quinkink** [comment] 2015-11-21 16:06
Hello,
I have had a go at compiling... but ha hah ha this is not as straight forward as I originally thought. When did you say the dirver would be pushed towards the main Raspi releases...
Cheers,
Mark.

**Comment by Quinkink** [comment] 2015-11-21 20:59
Hi again,
I figured I'd try and compile the driver from the kernel source:
>rpi-update
>rpi-source
>gcc 4.8.3
>sfxx make

However I am stuck at the make stage.
(this could be something obvious but not sure)
All the best,
Mark.

pi@raspberrypi ~/sfxx $ make
make[1]: Entering directory '/home/pi/linux-bc1669c846b629cface0aaa367afb2b9c6226faf'
make[1]: /usr/src/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc: Command not found
  CC [M]  /home/pi/sfxx/sfxx.o
/bin/sh: 1: /usr/src/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc: not found
scripts/Makefile.build:264: recipe for target '/home/pi/sfxx/sfxx.o' failed
make[2]: *** [/home/pi/sfxx/sfxx.o] Error 127
Makefile:1384: recipe for target '_module_/home/pi/sfxx' failed
make[1]: *** [_module_/home/pi/sfxx] Error 2
make[1]: Leaving directory '/home/pi/linux-bc1669c846b629cface0aaa367afb2b9c6226faf'
Makefile:46: recipe for target 'sfxx.ko' failed
make: *** [sfxx.ko] Error 2

**Comment by Quinkink** [comment] 2015-11-22 19:33
Good evening,
Sorry to post back here again if this is not a good place.
I had another crack at this today and corrected a path in the Makefile to suit my setup.
However this is what I now have: a syntax error somewhere, although very unsure exactly where.
Any ideas welcome,
Mark.

pi@raspberrypi ~/sfxx $ make
make[1]: Entering directory '/home/pi/linux-bc1669c846b629cface0aaa367afb2b9c6226faf'
/usr/src/raspberrypi/linux/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc: 1: /usr/src/raspberrypi/linux/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc: Syntax error: "(" unexpected
  CC [M]  /home/pi/sfxx/sfxx.o
/usr/src/raspberrypi/linux/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc: 1: /usr/src/raspberrypi/linux/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc: Syntax error: "(" unexpected
scripts/Makefile.build:264: recipe for target '/home/pi/sfxx/sfxx.o' failed
make[2]: *** [/home/pi/sfxx/sfxx.o] Error 2
Makefile:1384: recipe for target '_module_/home/pi/sfxx' failed
make[1]: *** [_module_/home/pi/sfxx] Error 2
make[1]: Leaving directory '/home/pi/linux-bc1669c846b629cface0aaa367afb2b9c6226faf'
Makefile:46: recipe for target 'sfxx.ko' failed
make: *** [sfxx.ko] Error 2

**Comment by chrisbura** [comment] 2016-01-17 09:36
Hi @Quinkink,

I was able to get it to compile by doing it in ubuntu and cross compiling for the raspberry pi. The bad news is that I had to recompile the entire kernel because the sfxx driver requires "crc8" which is not enabled in the default raspbian config. 

I haven't actually connected a sensor yet to test if it works though. I will upload my procedure to a gist once I determine if it works.

These are the links I followed. I have no idea if it's possible to add a module to an already compiled kernel so I effectively started from scratch.

https://www.raspberrypi.org/documentation/linux/kernel/building.md
https://www.raspberrypi.org/documentation/linux/kernel/configuring.md

**Comment by Quinkink** [comment] 2016-01-23 08:30
Hi @chrisbura,

Thank-you for your input. I'm not on the ball as far as compiling in concerned and I really need to set up a VM Linux and do the CC for the Raspi. I know this will be very time consuming and possibly frustrating as I forget to enable/disable key features and REDO FROM START a few times.

I had put this project on a back-burner but I would be please to know how it goes for you. Especially if you piece together a "fail-safe" How-To or even better a Rasbian style distrib with integrated Sensirion module (dream-on!)

All the best,
Mark.

**Comment by chrisbura** [comment] 2016-01-24 07:40
Here is my procedure for doing everything from scratch. It took me lots of trial and error and I used an extra SD card so I didn't mess up a running version.

https://gist.github.com/chrisbura/f82b9dcd8b5ed1679c13

Surely there must be an easier way. It should be theoretically possible to compile it all on the raspberry pi but the `sfxx` module NEEDS `crc8` and it is not included in the default kernel configuration. I don't know enough about this stuff to figure out how to only get `crc8` included without rebuilding everything!

I'll keep working on finding a better solution but for now this "works"...

**Comment by Quinkink** [comment] 2016-02-11 23:17
Thanks for the proceedure.

Installed VM : ubuntu 12.04

I have followed it through several time and always end up with:
FATAL: Module crc8 not found after the sudo modprobe crc8 command.

Whilst configuring the Kernel:
I find a reference to crc8 in the config under Library Routines>crc8 and tried both <*> and <M>
and then >$ make ARCH=arm CROSS_COMPILE=${CCPREFIX} zImage modules dtbs

The actual Sensirion sensor is getting a little dusty as it waits for a solution,
so far I have learned a lot but had no success!
I'll keep on looking.
All the best,

**Comment by chrisbura** [comment] 2016-02-12 03:12
Hi @Quinkink,

I've updated the gist to include the proper location for the module. Thanks for that.

After you build the kernel try running 

    cat Module.symvers | grep crc8

to make sure that the crc8 symbols were exported. You want to see `crc8` and `crc8_populate_msb`.

**Comment by Quinkink** [comment] 2016-02-14 21:51
Thank-you for all this.
I now have a compiled kernel with crc8 support.
>sudo modprobe crc8 [OK]
>sudo insmod sfxx.ko [OK]
>sudo i2cdetect -y 1 shows device in 40:40

However I'm back to square one with : 
"No sensors found!" 
"detecting sensors
couldn't find any sensors"

when I run  >python streaming_example.py or >python sync_example.py

I'll keep on working at it...

**Comment by chrisbura** [comment] 2016-02-15 02:59
Take a look at the `Makefile` to see the proper way to mount the sensors.

https://github.com/Sensirion/sfxx/blob/master/Makefile#L58

You are interested in this part

    echo $(MODULENAME) $(ADDRESS) | sudo tee /sys/bus/i2c/devices/i2c-$(I2C_BUSID)/new_device

Then the sensor is read like any file

https://github.com/Sensirion/sfxx/blob/master/Makefile#L69

    cat /sys/bus/i2c/devices/i2c-$(I2C_BUSID)/$(I2C_BUSID)-00$(ADDRESS_NR)/measured_value

The variables are defined in the `Makefile`

I'll hook up a sensor to get another procedure worked out for the last step after compiling the module.

**Comment by psachs** [comment] 2016-02-15 08:10
@Quinkink 
With the current implementation of the driver you first have to attach the sensors and then load the drivers to be able to connect to the sensors. Else it will not recognize any sensors and therefore won't create the i2c bus

**Comment by ychefla** [comment] 2016-05-17 21:36
Hey,

I'm exactly where Quinkink started... trying to get my sensirion sensor to work with RPi. In my case the sensor is SFM3000 series flow sensor.

Do you have any updates to this topic since FEB? I'm dreaming on not having to play with kernel stuff.

**Comment by honggoff** [comment] 2016-05-18 07:02
Yes, we published a tutorial on how to set up the flow sensor driver on a Raspberry Pi. With the latest Raspbian release it is now possible to only compile the driver without recompiling the kernel. Plus everything can be done on the Raspberry itself.

https://developer.sensirion.com/development-environment/raspberry-pi/flow-sensor-raspberry-tutorial/

Let me know if you have any questions.

**Comment by ychefla** [comment] 2016-05-18 21:18
Great thanks! I got maybe a bit further. I think  got everything installed, but "sync_example.py" still complains...

I get message: "No sensors found!"

I tried to print intermediate stuff from the driver to figure out why this happens. To me it seems that the code tries to access "/sys/bus/i2c/devices/1-0040/unit". I do have /sys/bus/i2c/devices/1-0040, but in there I have only: "modalias", "name", "subsystem" and "uevent", no "unit"

What could be wrong?

**Comment by ychefla** [comment] 2016-05-19 06:01
Because of that unit related error I tried disabling the function call that caused the error and instead 
defined the units on my own: 

sensirion_sensors.py - line 56
```
        unit = "foo"#self.read_file(unit_file).strip()
```

I did get further, but not all the way. Still got the "No sensors found!"

I put some printing to the sensirion_sensors.py - lines 110... 113

```
    print ("-------------")
    print [loaded_sensors[0]]
    print [loaded_sensors[0].is_available()]
    print ("-------------")
```
and when running the "sync_example.py" I get:

```
$ sudo python sync_example.py
-------------
[<sensirion_sensors.SFxxSensor object at 0x76a3d0d0>]
[False]
-------------
No sensors found!
```

Is it so that the sensor is sort of found, but not available?

**Comment by Quinkink** [comment] 2016-05-19 06:57
Hey!
Just to let you know.... I had all but given up and then:

I downloaded latest Rasbian distro and put image on SD
I reconfigured network connection and keyboard
installed git
then followed the [https://developer.sensirion.com/development-environment/raspberry-pi/flow-sensor-raspberry-tutorial/](url) to the letter.
Sensor is found and sync_example.py works great.
I am using a SFxxSensor[Pa] Sensirion SDP610

All the best.

**Comment by honggoff** [comment] 2016-05-19 08:28
@ychefla I doubt that the error is in the python script, but that indeed the driver could not find the sensor. It might simply be a wiring problem. Use `i2cdetect` to check if the sensor is connected correctly:

```
sudo apt-get install i2c-tools
i2cdetect -y 1
```

This should list the address 0x40 as connected. You can also compare the output when the sensor is disconnected vs. when it is connected. If the sensor is not connected while instantiating the driver, the probing will fail and the relevant files in the sysfs will not be created (unit and measured_value). Also it will print an error message to the kernel log, which you can inspect with `dmesg`.

Another thing you can do, is make sure there is no error message after loading the driver with `sudo insmod sfxx/sfxx.ko`. After that command, the driver should be listed when you run `lsmod`.

**Comment by ychefla** [comment] 2016-05-19 08:53
Hi,

I can't access the system now, but

I have tested that i2cdetect -y 1 and it works fine and shows the 0x40 as
the address.

I'm not saying that there would be problem with the driver sw. The prints
were just to provide as detaild info as possible.

I'll try your suggestions later today

Thanks

On Thursday, 19 May 2016, honggoff <notifications@github.com> wrote:

> @ychefla <https://github.com/ychefla> I doubt that the error is in the
> python script, but that indeed the driver could not find the sensor. It
> might simply be a wiring problem. Use i2cdetect to check if the sensor is
> connected correctly:
>
> sudo apt-get install i2c-tools
> i2cdetect -y 1
>
> This should list the address 0x40 as connected. You can also compare the
> output when the sensor is disconnected vs. when it is connected. If the
> sensor is not connected while instantiating the driver, the probing will
> fail and the relevant files in the sysfs will not be created (unit and
> measured_value). Also it will print an error message to the kernel log,
> which you can inspect with dmesg.
>
> Another thing you can do, is make sure there is no error message after
> loading the driver with sudo insmod sfxx/sfxx.ko. After that command, the
> driver should be listed when you run lsmod.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Sensirion/libsensors-python/issues/2#issuecomment-220260034>
>


-- 
Sent from iPad

**Comment by ychefla** [comment] 2016-05-19 19:56
Got it to work!!!
Thank you!

**Comment by honggoff** [comment] 2016-05-19 20:06
Good to hear. Could you let me know what was the problem or how you fixed it? I could then update our tutorial.

**Comment by ychefla** [comment] 2016-05-19 20:27
The problem was me :)
I went through the steps too fast and didn't read properly the outputs. I believe the root cause was too old compiler. After updating that, I deleted everything and restarted. Now it works like a charm.

Thanks again :)

**Comment by ychefla** [comment] 2016-05-19 20:28
I must add... I'm surprised that natively there is only support for SMBus and thus very limited ways to communicate via I2C.

**Comment by honggoff** [comment] 2016-05-20 08:47
I'll close this issue now with another link to our tutorial: https://developer.sensirion.com/development-environment/raspberry-pi/flow-sensor-raspberry-tutorial/
Please open a new issue if you encounter new problems.

**Closed by honggoff** 2016-05-20 08:47 UTC
